[package]
name = "rnd_is"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6"
actix-web = "4"
mime = "0.3"
rand = "0.8"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
