name: CI

on:
  push:
    branches:
      - main

jobs:

  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install nightly          

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Test
        run: |
          cargo check
          cargo clippy -- -D warnings
          cargo test --all         

      - name: Run cloud build
        run: |
          export CLOUDSDK_CORE_DISABLE_PROMPTS=1
          gcloud builds submit . --config cloudbuild.yaml --timeout=1200 --machine-type=e2-highcpu-8